### PR TITLE
changing location of setup files to setup/kinase/pdb/ligand

### PR DESCRIPTION
**Pull request by juliebehr**

### CODE REVIEW

**Comment by jchodera** [comment]
Looks good to me!  

Are you going to call `main()` externally?  If so, we might want to change that name to something like `setup_yank_calculation()`.

**Comment by juliebehr** [comment]
It's an easy enough fix that we might as well change it regardless -- fixing now.

**Comment by jchodera** [comment]
Looks good to me!  Merge when ready.

**Comment by jchodera** [comment]
Might want to update the `README.md` with some info too, though!

**Comment by jchodera** [comment]
This can be merged when ready!

**Pull request merged**
